---
title: "R Markdown Homework"
author: "Talha ÜNLÜ"
date: "05 08 2020"
output: html_document
---

```{r setup, include=FALSE}

```

## About Me

I am Talha. I am senior student at Bogazici University and planning to graduate January 2021.I am currently working as a sales analyst in Nike. Manipulating data and extracting meaningful information is very effective and important in the business world. I want to develop my skills in this subject and create a career parallel to this. 

[Linkedln Profile](https://www.linkedin.com/in/talha-%C3%BCnl%C3%BC1/) 

## useR! 2020: Doing Journalism with R (B. Witzenberger)
Benedict Witzenberger explains how they do journalism using r programming. First of all, a very interesting topic and a creative application. Although the organization is made up of people of social science origin, there are few digital people. It is not surprising that an organization that is a journalist with a different perspective does this work with people from different disciplines.
Witzenberger talks about dividing the projects into two. Short term and long term. He then explained his workflows and mentioned four main parts.
  
  * Finding suitable data 
  * Data wrangling with R
  * Data analysis with R
  * Data visualization with R
  
They mentioned the three libraries they specifically used when accessing the appropriate data, such as **{readr}**, **{rvest}** and **{jsonlite}**.
He then mentioned that the library they use the most in data wrangling operations is **{tidyverse}**. Finally, he said that **"ggplot2"** is used very much in data visulization.  

[useR! 2020: Doing Journalism with R](https://www.youtube.com/watch?v=1bmdHy5vtfY)
  
## How the BBC Visual and Data Journalism team works with graphics in R

After watching the video above, I was interested in using R programming in journalism and I continued to research, and this article appeared. The BBC has a team called visual and data team and they use R a lot in their work. Especially they use the ggplot2 package. Because they talk about being able to produce complex and reproducible contents with the ggplot2 package. They especially point out that being able to produce reproducible content gives them an exponential gains.

Even in 2018, the data team concentrated on the ggplot2 package and produced new packages. These packages are produced by taking reference from ggplot2 and since they are open source, anyone can use them. The names of the packages they produce are **bbplot** and **R cookbook**.

I learned from this information that users can also produce packages in R and share it with everyone.

[How the BBC Visual and Data Journalism team works with graphics in R](https://medium.com/bbc-visual-and-data-journalism/how-the-bbc-visual-and-data-journalism-team-works-with-graphics-in-r-ed0b35693535)

## Why learn dplyr for everyday data analysis ?

In this article, Kan Nishida highlights how effective the dplyr package is in analyzing data and manipulating data. In the first paragraph of the article, with a short code, it shows a simple use of the dplyr package and talks about what the pipe **'%>%'** means. Then he talks about the data and how complex we want to find, thanks to the dplyr package, how we can manipulate the data without complicating the code. By giving examples from past Oracle experiences, it gives information that this work is much more challenging with SQL codes.

[Why learn dplyr for everyday data analysis ?](https://blog.exploratory.io/introduction-11fdd17af04)

## 









